---
title: "Применение контрольных карт для мониторинга аварийных прерываний ИТ-услуг"
author: "Тушавин В. А."
date: "09 06 2020"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Вычисления к статье

Ниже приводятся вычисления для построения графиков в статье "Применение контрольных карт для мониторинга аварийных прерываний ИТ-услуг"


```{r main}
library(qcc)
library(readr)
require(lubridate)
data <- read_csv("data.csv", col_types = cols(actualstart = col_datetime(format = "%Y-%m-%d %H:%M:%S"), actualfinish = col_datetime(format = "%Y-%m-%d %H:%M:%S")))
data<-data[order(data$actualstart),]
data$badtime<-data$actualfinish-data$actualstart
data$year<-year(data$actualstart)
data$month<-month(data$actualstart)
data$diff<-0
data$diff[-1]<- diff(data$actualstart)
uchart<-aggregate(badtime~month+year,data=data,sum)
uchart<-uchart[1:13,]
uchart<-rbind(uchart,data.frame(month=c(1,5,8,11,12),year=2018,badtime=0))
uchart<-rbind(uchart,data.frame(month=c(1:5,12),year=2019,badtime=0))
uchart$total<-days_in_month(uchart$month)*24*60
uchart<-uchart[order(uchart$year,uchart$month),]
old <- qcc.options() 
qcc.options(bg.margin="white")
qcc(uchart$badtime,sizes=uchart$total,type="u",title="U-chart")
qcc(data$diff[25:37], type="g",title="G-chart 2019",confidence.level=0.95)
qcc.options(old)

```

## Расчеты статистики

```{r}
library(ADGofTest)
(ad.test(data$diff[25:37],pgeom,prob=1/mean(data$diff[25:37])))
(log(0.025)/(log(1-1/17833.85))-1)
(log(1-0.025)/(log(1-1/17833.85)))
```

